package com.sourcefuse.jarc.services.notificationservice.configuration.connections;

import java.util.HashMap;
import java.util.Map;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.client.HttpServerErrorException;

import com.sourcefuse.jarc.services.notificationservice.providers.push.socketio.types.SocketConnectionConfig;

import io.socket.client.IO;
import io.socket.client.Socket;

@Service
@ConditionalOnProperty(value = "notification.provider.push", havingValue = "SocketIoProvider")
public class SocketIoConfig implements SocketConnectionConfig {

	Socket socket;

	@Value("${socket.default-path:#{null}}")
	String defaultPath;

	private SocketIoConfig() {
		try {
			// Configure and connect to the Socket.IO server
			IO.Options options = new IO.Options();
			options.path = "/socket.io";
			Map<String, String> auth = new HashMap<>();
			auth.put("token",
					"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQyNjJlMWJmLTFiZTgtM2JhYy1jZTQ5LTE2NjMyNGRmMWUzMyIsImZpcnN0TmFtZSI6Ik9hc2lzIiwibGFzdE5hbWUiOiJBZG1pbiIsIm1pZGRsZU5hbWUiOm51bGwsInVzZXJuYW1lIjoib2FzaXNfYWRtaW5Ac291cmNlZnVzZS5jb20iLCJlbWFpbCI6Im9hc2lzX2FkbWluQHNvdXJjZWZ1c2UuY29tIiwicGhvbmUiOm51bGwsImxhc3RMb2dpbiI6bnVsbCwiZ2VuZGVyIjpudWxsLCJkZWZhdWx0VGVuYW50SWQiOiJmZjE1MjlmYy0wZWE1LTkwMmYtNjU5ZS0zZDJmZjA0ZGE3NTIiLCJhdXRoQ2xpZW50SWQiOjEsInRlbmFudElkIjoiZmYxNTI5ZmMtMGVhNS05MDJmLTY1OWUtM2QyZmYwNGRhNzUyIiwidXNlclRlbmFudElkIjoiNGE2MWYzYTAtMGVlMi01MzM4LTU2M2YtMzA0NjkzNzQyODQ1Iiwic3RhdHVzIjoxLCJ0ZWFtcyI6W10sInBlcm1pc3Npb25zIjpbIkNyZWF0ZVRlbmFudCIsIlVwZGF0ZVRlbmFudCIsIkRlbGV0ZVRlbmFudCIsIkNyZWF0ZUFueVVzZXIiLCJVcGRhdGVBbnlVc2VyIiwiRGVsZXRlQW55VXNlciIsIlZpZXdSb2xlcyIsIkNyZWF0ZVJvbGVzIiwiVXBkYXRlUm9sZXMiLCJEZWxldGVSb2xlcyIsIkNyZWF0ZVRlbmFudENvbmZpZyIsIlZpZXdUZW5hbnRDb25maWciLCJVcGRhdGVUZW5hbnRDb25maWciLCJEZWxldGVUZW5hbnRDb25maWciLCJDcmVhdGVXb3Jrc3BhY2UiLCJDcmVhdGVGb2xkZXIiLCJWaWV3Rm9sZGVyIiwiVXBkYXRlRm9sZGVyIiwiRGVsZXRlRm9sZGVyIiwiQ3JlYXRlQm9hcmQiLCJEZWxldGVCb2FyZCIsIkNyZWF0ZUJvYXJkVmlldyIsIlZpZXdCb2FyZFZpZXciLCJVcGRhdGVCb2FyZFZpZXciLCJEZWxldGVCb2FyZFZpZXciLCJDcmVhdGVCb2FyZENvbHVtbiIsIlZpZXdCb2FyZENvbHVtbiIsIlVwZGF0ZUJvYXJkQ29sdW1uIiwiRGVsZXRlQm9hcmRDb2x1bW4iLCJDcmVhdGVDb2x1bW5UeXBlIiwiVmlld0NvbHVtblR5cGUiLCJVcGRhdGVDb2x1bW5UeXBlIiwiRGVsZXRlQ29sdW1uVHlwZSIsIkNyZWF0ZUdyb3VwIiwiVmlld0dyb3VwIiwiQ3JlYXRlVGFzayIsIlZpZXdUYXNrIiwiQ3JlYXRlVGFza0NvbHVtblZhbHVlIiwiVmlld1Rhc2tDb2x1bW5WYWx1ZSIsIlVwZGF0ZVRhc2tDb2x1bW5WYWx1ZSIsIkRlbGV0ZVRhc2tDb2x1bW5WYWx1ZSIsIkNyZWF0ZUJvYXJkTWVtYmVyIiwiVmlld0JvYXJkTWVtYmVyIiwiVXBkYXRlQm9hcmRNZW1iZXIiLCJEZWxldGVCb2FyZE1lbWJlciIsIkNyZWF0ZU5vdGlmaWNhdGlvbiIsIlZpZXdOb3RpZmljYXRpb24iLCJVcGRhdGVOb3RpZmljYXRpb24iLCJEZWxldGVOb3RpZmljYXRpb24iLCJDYW5HZXROb3RpZmljYXRpb25BY2Nlc3MiLCJDcmVhdGVXb3Jrc3BhY2VNZW1iZXIiLCJWaWV3V29ya3NwYWNlTWVtYmVyIiwiVXBkYXRlV29ya3NwYWNlTWVtYmVyIiwiRGVsZXRlV29ya3NwYWNlTWVtYmVyIiwiRG93bmxvYWRUYXNrRmlsZSIsIkNyZWF0ZVRhc2tGaWxlIiwiRGVsZXRlVGFza0ZpbGUiLCJWaWV3VGFza0ZpbGUiLCJDcmVhdGVNZXNzYWdlIiwiVmlld01lc3NhZ2UiLCJVcGRhdGVNZXNzYWdlIiwiRGVsZXRlTWVzc2FnZSIsIkNyZWF0ZU1lc3NhZ2VSZWNpcGllbnQiLCJWaWV3TWVzc2FnZVJlY2lwaWVudCIsIlVwZGF0ZU1lc3NhZ2VSZWNpcGllbnQiLCJEZWxldGVNZXNzYWdlUmVjaXBpZW50IiwiVmlld1dvcmtzcGFjZUxpc3QiLCJDcmVhdGVEYXNoYm9hcmQiLCJDcmVhdGVEYXNoYm9hcmRXaWRnZXQiLCJVcGRhdGVEYXNoYm9hcmRXaWRnZXQiLCJEZWxldGVEYXNoYm9hcmRXaWRnZXQiLCJWaWV3RGFzaGJvYXJkV2lkZ2V0IiwiVmlld0JvYXJkTGlzdCIsIlZpZXdEYXNoYm9hcmRNZW1iZXIiLCJWaWV3RGFzaGJvYXJkTGlzdCIsIkNyZWF0ZU1lc3NhZ2UiLCJWaWV3TWVzc2FnZSIsIlVwZGF0ZU1lc3NhZ2UiLCJEZWxldGVNZXNzYWdlIiwiQ3JlYXRlTWVzc2FnZVJlY2lwaWVudCIsIlZpZXdNZXNzYWdlUmVjaXBpZW50IiwiVXBkYXRlTWVzc2FnZVJlY2lwaWVudCIsIkRlbGV0ZU1lc3NhZ2VSZWNpcGllbnQiLCJDcmVhdGVNYXN0ZXJCb2FyZFRlbXBsYXRlIiwiRGVsZXRlRGFzaGJvYXJkTWVtYmVyIiwiVmlld0F1ZGl0IiwiVXBkYXRlV29ya3NwYWNlTGlzdCIsIkRlbGV0ZVdvcmtzcGFjZUxpc3QiLCJXb3Jrc3BhY2VPd25lckxpc3QiLCJVcGRhdGVCb2FyZExpc3QiLCJCb2FyZE93bmVyTGlzdCIsIlVwZGF0ZUdyb3VwTGlzdCIsIkRlbGV0ZUdyb3VwTGlzdCIsIlVwZGF0ZVRhc2tMaXN0IiwiRGVsZXRlVGFza0xpc3QiLCJDcmVhdGVBdWRpdCIsIlJlcXVlc3RBY2Nlc3MiLCJDcmVhdGVOb3RpZmljYXRpb25QcmVmZXJlbmNlcyIsIlVwZGF0ZU5vdGlmaWNhdGlvblByZWZlcmVuY2VzIiwiVmlld05vdGlmaWNhdGlvblByZWZlcmVuY2VzIiwiRGVsZXRlTm90aWZpY2F0aW9uUHJlZmVyZW5jZXMiLCJWaWV3VXNlckxldmVsUmVzb3VyY2VMaXN0IiwiQ2FuQ29udmVydEZpbGUiLCJWaWV3Tm90aWZpY2F0aW9uVGVtcGxhdGUiLCJDcmVhdGVOb3RpZmljYXRpb25UZW1wbGF0ZSIsIlVwZGF0ZU5vdGlmaWNhdGlvblRlbXBsYXRlIiwiRGVsZXRlTm90aWZpY2F0aW9uVGVtcGxhdGUiLCJWaWV3T3duVGVuYW50IiwiVmlld1RlbmFudFVzZXIiLCJWaWV3VXNlclRlbmFudFByZWZlcmVuY2UiLCJVcGRhdGVVc2VyVGVuYW50UHJlZmVyZW5jZSIsIkNyZWF0ZVdvcmtmbG93IiwiVXBkYXRlV29ya2Zsb3ciLCJWaWV3V29ya2Zsb3ciLCJEZWxldGVXb3JrZmxvdyIsIkdldEN1cnJlbmN5IiwiRXhwb3J0UFBUIiwiQ3JlYXRlVGFnIiwiVXBkYXRlVGFnIiwiRGVsZXRlVGFnIiwiVmlld1RhZyIsIkNyZWF0ZVdvcmtzcGFjZUNvbHVtbiIsIlVwZGF0ZVdvcmtzcGFjZUNvbHVtbiIsIkRlbGV0ZVdvcmtzcGFjZUNvbHVtbiIsIlZpZXdXb3Jrc3BhY2VDb2x1bW4iLCJWaWV3Rm9ybSIsIlZpZXdGb3JtTGlzdCIsIkZvcm1DcmVhdGUiLCJGb3JtVXBkYXRlIiwiRm9ybURlbGV0ZSIsIlZpZXdXb3Jrc3BhY2VUYXNrcyIsIkV4ZWN1dGVXb3JrZmxvdyIsIkNyZWF0ZUNhbGVuZGFyIiwiVXBkYXRlQ2FsZW5kYXJMaXN0IiwiRGVsZXRlQ2FsZW5kYXJMaXN0IiwiQ3JlYXRlSG9saWRheSIsIlZpZXdIb2xpZGF5TGlzdCIsIlVwZGF0ZUhvbGlkYXlMaXN0IiwiRGVsZXRlSG9saWRheUxpc3QiLCJWaWV3Q2FsZW5kYXJMaXN0IiwiVmlld0hvbGlkYXlMaXN0IiwiVXBkYXRlR3JvdXBUaW1lbGluZVNldHRpbmdzIiwiVXBkYXRlR3JvdXBCYXNlbGluZVNldHRpbmdzIiwiQ3JlYXRlV29ya3NwYWNlVGVtcGxhdGUiLCJWaWV3V29ya3NwYWNlVGVtcGxhdGUiLCJDcmVhdGVEYXNoYm9hcmRUZW1wbGF0ZSIsIlZpZXdEYXNoYm9hcmRUZW1wbGF0ZSIsIlZpZXdXb3Jrc3BhY2VHcm91cCIsIlZpZXdVc2VyR3JvdXBMaXN0IiwiVmlld1VzZXJHcm91cCIsIkNyZWF0ZVVzZXJHcm91cCIsIlVwZGF0ZVVzZXJHcm91cCIsIkRlbGV0ZVVzZXJHcm91cCIsIkFkZE1lbWJlclRvVXNlckdyb3VwIiwiVXBkYXRlTWVtYmVySW5Vc2VyR3JvdXAiLCJSZW1vdmVNZW1iZXJGcm9tVXNlckdyb3VwIiwiQ3JlYXRlUmVzb3VyY2VBbGxvY2F0aW9uIiwiVXBkYXRlUmVzb3VyY2VBbGxvY2F0aW9uTGlzdCIsIkRlbGV0ZVJlc291cmNlQWxsb2NhdGlvbkxpc3QiLCJHZXRSZXNvdXJjZUFsbG9jYXRpb25MaXN0IiwiQ3JlYXRlRGF0YXNldCIsIlVwZGF0ZURhdGFzZXRMaXN0IiwiRGVsZXRlRGF0YXNldExpc3QiLCJWaWV3RGF0YXNldExpc3QiLCJDcmVhdGVEYXRhc2V0TWFwcGluZyIsIlVwZGF0ZURhdGFzZXRNYXBwaW5nTGlzdCIsIkRlbGV0ZURhdGFzZU1hcHBpbmd0TGlzdCIsIlZpZXdEYXRhc2V0TWFwcGluZ0xpc3QiLCJVcGRhdGVEYXRhc2V0IiwiVmlld0RhdGFzZXQiLCJEZWxldGVEYXRhc2V0IiwiVmlld0V4dGVybmFsVXNlck1hcHBpbmdMaXN0IiwiVmlld0RhdGFzZXREYXRhIiwiVXBkYXRlQm9hcmRGaWx0ZXIiLCJEYXRhc2V0TWFwcGluZ0RhdGFQdWJsaXNoIiwiQ3JlYXRlQ3JpdGljYWxQYXRoIiwiVmlld0NyaXRpY2FsUGF0aCIsIlZpZXdDcml0aWNhbFBhdGhMaXN0IiwiVXBkYXRlQ3JpdGljYWxQYXRoIiwiRGVsZXRlQ3JpdGljYWxQYXRoIiwiVmlld1Jlc291cmNlQWxsb2NhdGlvbkxpc3QiLCJDcmVhdGVSZXNvdXJjZVBsYWNlaG9sZGVyIiwiVmlld1Jlc291cmNlUGxhY2Vob2xkZXIiLCJWaWV3UmVzb3VyY2VQbGFjZWhvbGRlckxpc3QiLCJVcGRhdGVSZXNvdXJjZVBsYWNlaG9sZGVyIiwiRGVsZXRlUmVzb3VyY2VQbGFjZWhvbGRlciIsIkNyZWF0ZU9yZ2FuaXphdGlvblJvbGUiLCJWaWV3T3JnYW5pemF0aW9uUm9sZSIsIkRlbGV0ZU9yZ2FuaXphdGlvblJvbGUiLCJVcGRhdGVPcmdhbml6YXRpb25Sb2xlIiwiVmlld09yZ2FuaXphdGlvblJvbGVMaXN0IiwiVmlld1Jlc291cmNlQ291bnRMaXN0IiwiQ2xlYXJDYWNoZSJdLCJyb2xlIjoiMCIsImF1dGhQcm92aWRlciI6ImludGVybmFsIiwiaWF0IjoxNjg1NTQzNzM1LCJleHAiOjE2ODU1NDU1MzUsImlzcyI6InJha3V0ZW5fYXV0aCJ9.R9cbU2w8NSX-Y62upggZ4K6IGX4G0d1i0-9X4sU0mOs");
			options.auth = auth;
			String serverUrl = "http://127.0.0.1:3009"; // Replace with your actual Socket.IO server URL
			socket = IO.socket(serverUrl, options);
			socket.connect();
			if (!socket.connected()) {
				throw new RuntimeException("Failed to initialize Socket.IO client connection");
			}
		} catch (Exception e) {
			throw new RuntimeException("Failed to initialize Socket.IO client: " + e.getMessage());
		}
	}

	@Override
	public Socket getSocket() {
		if (socket == null || !socket.connected()) {
			throw new HttpServerErrorException(HttpStatus.PRECONDITION_FAILED, "Lost the socket connection");
		}
		return socket;
	}

	@Override
	public String getDefaultPath() {
		return this.defaultPath;
	}
}
