package com.sourcefuse.jarc.services.authservice.enums;

public enum AuthErrorKeys {
  CODE_EXPIRED,
  TOKEN_EXPIRED,
  TOKEN_INVALID,
  CLIENT_INVALID,
  CLIENT_VERIFICATION_FAILED,
  CLIENT_SECRET_MISSING,
  CLIENT_USER_MISSING,
  INVALID_CREDENTIALS,
  USER_VERIFICATION_FAILED,
  UNKNOWN_ERROR,
  WRONG_PASSWORD,
  KEY_INVALID,
  OTP_INVALID,
  OTP_EXPIRED;
}
